---

- name: Ensure existing cloud tenant image does not exist
  vars:
    checksum_differs: >-
      {{ glance_metadata[image_key]["checksum"] != local_checksums[checksum_key] }}
    force_rebuild: "{{ item.force_rebuild | default(os_images_force_rebuild) | bool }}"
  os_image:
    auth_type: "{{ os_images_auth_type }}"
    auth: "{{ os_images_auth }}"
    name: "{{ image_key }}"
    state: absent
  when:
    - image_key in glance_metadata
    - force_rebuild or checksum_differs
  tags: clean
