---

- name: Ensure existing cloud tenant image does not exist
  vars:
    checksum_differs: >-
      {{ glance_metadata[image_key]["checksum"] != local_checksums[checksum_key] }}
  os_image:
    auth_type: "{{ os_images_auth_type }}"
    auth: "{{ os_images_auth }}"
    name: "{{ image_key }}"
    state: absent
  when:
    - image_key in glance_metadata
    - checksum_differs
  tags: clean
