---
- name: Ensure Ansible uses virtualenv python interpreter
  set_fact:
    ansible_python_interpreter: "{{ os_images_venv }}/bin/python"

- name: Ensure download cache dir exists
  file: 
    path: "{{ os_images_cache }}"
    state: directory

- name: Generate per-image cache directories
  file:
    path: "{{ os_images_cache }}/{{ item.name }}"
    state: directory
  with_items: "{{ os_images_list }}"

- name: Install a suitable version of diskimage-builder
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version or omit }}"
    state: present
    virtualenv: "{{ os_images_venv }}"
  with_items:
    - name: diskimage-builder
      version: "{{ os_images_dib_version }}"

- name: Git clone any additional image element repos
  git: 
    repo: "{{ item.repo }}"
    dest: "{{ item.local }}"
    version: "{{ item.version | default('HEAD') }}"
  with_items: "{{ os_images_git_elements }}"

- name: Generate diskimage-builder images
  command: >
    env
    {%if os_images_elements is defined %}ELEMENTS_PATH="{{ os_images_elements }}"{% endif %}
    disk-image-create
      {%if item.size is defined %}--image-size {{ item.size }}{% endif %}
      {{ os_images_common }}
      {{ item.elements | join( ' ' ) }} -o {{ item.name }}
  args:
    chdir: "{{ os_images_cache }}/{{ item.name }}"
    creates: "{{ os_images_cache }}/{{ item.name }}/{{ item.name }}.qcow2"
  environment: "{{ item.env|default({}) }}"
  with_items: "{{ os_images_list }}"

- name: Upload cloud tenant images
  os_image: 
    auth_type: "{{ os_images_auth_type }}"
    auth: "{{ os_images_auth }}"
    name: "{{ item.name }}"
    state: present
    is_public: yes
    container_format: bare
    disk_format: qcow2
    filename: "{{ os_images_cache }}/{{ item.name }}/{{ item.name }}.qcow2"
    properties:
      cpu_arch: x86_64
  with_items: "{{ os_images_list }}"

# This variable is unset before we set it, and it does not appear to be
# possible to unset a variable in Ansible.
- name: Set a fact to reset the Ansible python interpreter
  set_fact:
    ansible_python_interpreter: /usr/bin/python
